"""
EDA stage for the Olist outcome-risk project.

This script checks the candidate targets, explores likely drivers of bad
reviews, and writes a Markdown report with supporting tables and plots.

Run:
    python -m src.eda.run_eda

Outputs (all under output/eda/):
    summary.md          human-readable findings with key numbers
    tables/*.csv         supporting aggregated tables
    figures/*.png        supporting plots

Design intent: this script reports measured facts. The higher-level
interpretation lives in docs/problem_framing.md, docs/eda_findings.md, and
README.md. Keeping that split makes it easier to separate evidence from
judgment.

Sections (see each section_* function's docstring for detail):
     1. Data quality checks
     2. Target candidate distributions (bad_review, is_late, canceled)
     3. How related are the candidate targets?
     4. Seller-level variance (is bad_review concentrated in a few sellers?)
     5. Product category variance
     6. Price, freight, and payment structure
     7. Customer-seller distance
     8. Time trends
     9. Product-level concentration
    10. Geographic patterns (buyer/seller state, city, lane)
    11. Business impact: revenue at risk and repurchase
    12. Qualitative signal: what do bad-but-on-time reviews say?
    13. LLM-categorized complaint reasons (src/nlp/categorize_reviews.py output)
"""

import sys
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.data.loader import (
    RAW_DIR, load_raw, build_order_level_table, build_seller_level_table,
    build_product_level_table,
)

warnings.filterwarnings("ignore")

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output" / "eda"
FIG_DIR = OUTPUT_DIR / "figures"
TABLE_DIR = OUTPUT_DIR / "tables"
NLP_CATEGORIES_PATH = OUTPUT_DIR.parent / "nlp" / "review_categories.csv"

plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.3


def savefig(fig, name):
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    path = FIG_DIR / f"{name}.png"
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    return path.relative_to(OUTPUT_DIR)


def save_table(df, name):
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    path = TABLE_DIR / f"{name}.csv"
    df = df.copy()
    float_cols = df.select_dtypes(include=["float64", "float32", "Float64"]).columns
    df[float_cols] = df[float_cols].round(4)
    df.to_csv(path, index=False)
    return path.relative_to(OUTPUT_DIR)


def weighted_std(values, weights):
    """Volume-weighted standard deviation.

    Used to compare how much bad-review rates vary across groupings, such as
    seller vs. category. Weighting by order count avoids overreacting to tiny
    groups with unstable rates.
    """
    avg = np.average(values, weights=weights)
    return np.sqrt(np.average((values - avg) ** 2, weights=weights))


def grouped_bad_review_rate(df, group_col, min_orders=30):
    """Bad-review rate by group, keeping only groups with enough orders.

    This is used for simple categorical cuts such as category, state, and city.
    Seller and product sections use richer helper tables from loader.py.
    """
    sub = df.dropna(subset=[group_col, "bad_review"])
    return (
        sub.groupby(group_col)
        .agg(n_orders=("order_id", "count"), bad_review_rate=("bad_review", "mean"))
        .query("n_orders >= @min_orders")
        .sort_values("bad_review_rate", ascending=False)
    )


class Report:
    """Collects Markdown lines and writes the report at the end."""
    def __init__(self):
        self.lines = ["# EDA Summary\n", "Auto-generated by `src/eda/run_eda.py`. Do not hand-edit.\n"]

    def h2(self, text):
        self.lines.append(f"\n## {text}\n")

    def p(self, text):
        self.lines.append(f"{text}\n")

    def table_ref(self, caption, rel_path):
        self.lines.append(f"\n*{caption}* -> `{rel_path}`\n")

    def fig_ref(self, caption, rel_path):
        self.lines.append(f"\n*{caption}* -> `{rel_path}`\n")

    def write(self, path):
        path.write_text("\n".join(self.lines))


# ---------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------

def section_data_quality(raw, df, report: Report):
    """Check missing values and known data-quality issues."""
    report.h2("1. Data quality checks")

    n_orders = len(df)
    report.p(f"- Total orders: {n_orders:,}")

    status_counts = df["order_status"].value_counts()
    rel = save_table(status_counts.rename("count").reset_index().rename(columns={"index": "order_status"}),
                      "order_status_counts")
    report.table_ref("Order status counts", rel)

    key_cols = [
        "primary_category", "total_item_price", "total_freight_value",
        "primary_payment_type", "max_installments", "customer_lat", "customer_lng",
        "n_distinct_sellers",
    ]
    missing = df[key_cols].isna().mean().sort_values(ascending=False) * 100
    report.p("\nMissing values in candidate pre-outcome features:\n")
    for col, pct in missing.items():
        report.p(f"- `{col}`: {pct:.2f}%")

    n_missing_geo = df["customer_lat"].isna().sum()
    report.p(f"\n- Customer zip prefixes with no geolocation match: {n_missing_geo:,} ({n_missing_geo/n_orders*100:.2f}%)")

    n_zero_installments = (raw["order_payments"]["payment_installments"] == 0).sum()
    report.p(f"- Payment rows with `payment_installments == 0`: {n_zero_installments:,} "
             f"({n_zero_installments/len(raw['order_payments'])*100:.3f}% of payment rows).")
    if n_zero_installments > 0:
        zero_inst_types = raw["order_payments"].loc[
            raw["order_payments"]["payment_installments"] == 0, "payment_type"
        ].value_counts()
        rel = save_table(zero_inst_types.rename("count").reset_index().rename(columns={"index": "payment_type"}),
                          "zero_installment_payment_types")
        report.table_ref("Payment types among 0-installment rows", rel)

    geo = raw["geolocation"]
    n_dupe = geo.duplicated().sum()
    report.p(f"\n- Geolocation table: {len(geo):,} rows, {n_dupe:,} exact duplicates "
             f"({n_dupe/len(geo)*100:.1f}%). The pipeline uses zip-prefix centroids for location features.")


def section_target_candidates(df, report: Report):
    """Show how common each candidate bad outcome is."""
    report.h2("2. Target candidate distributions")

    review_dist = df["review_score"].value_counts(dropna=False).sort_index()
    rel = save_table(review_dist.rename("count").reset_index().rename(columns={"index": "review_score"}),
                      "review_score_distribution")
    report.table_ref("Review score distribution (including NaN = no review)", rel)

    n_reviewed = df["review_score"].notna().sum()
    bad_review_rate = df["bad_review"].mean()
    report.p(f"- Orders with a review score: {n_reviewed:,} / {len(df):,} ({n_reviewed/len(df)*100:.1f}%)")
    report.p(f"- `bad_review` (score<=2) rate among reviewed orders: {bad_review_rate*100:.2f}%")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    review_dist.dropna().plot(kind="bar", ax=ax, color="#4C72B0")
    ax.set_xlabel("review_score")
    ax.set_ylabel("count")
    ax.set_title("Review score distribution")
    rel = savefig(fig, "review_score_distribution")
    report.fig_ref("Review score histogram", rel)

    n_delivered = df["order_delivered_customer_date"].notna().sum()
    late_rate = df["is_late"].mean()
    report.p(f"\n- Orders with a delivered date: {n_delivered:,} / {len(df):,} ({n_delivered/len(df)*100:.1f}%)")
    report.p(f"- `is_late` rate among delivered orders: {late_rate*100:.2f}%")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    df["days_late"].clip(-30, 60).dropna().hist(bins=60, ax=ax, color="#DD8452")
    ax.axvline(0, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("days late (negative = early), clipped to [-30, 60]")
    ax.set_title("Delivery lateness distribution")
    rel = savefig(fig, "days_late_distribution")
    report.fig_ref("Days-late histogram (delivered orders only)", rel)

    cancel_rate = df["is_canceled_or_unavailable"].mean()
    report.p(f"\n- `is_canceled_or_unavailable` rate (all orders): {cancel_rate*100:.2f}%")

    df["bad_outcome_any"] = (
        df["bad_review"].fillna(False).astype(bool)
        | df["is_late"].fillna(False).astype(bool)
        | df["is_canceled_or_unavailable"]
    )
    report.p(f"- Composite `bad_outcome_any` (any of the above) rate (all orders): {df['bad_outcome_any'].mean()*100:.2f}%")


def section_target_overlap(df, report: Report):
    """Check whether low reviews, lateness, and cancellations describe the same problem."""
    report.h2("3. How related are the candidate targets?")
    report.p("Key question: are low reviews, late delivery, and cancellations close enough "
              "to combine into one target, or should they stay separate?\n")
    report.p("**Leakage note:** `is_late` is only known after delivery, so it cannot be used "
              "directly in a before-the-fact model. This section checks whether lateness is "
              "important enough to build advance-looking proxies, such as a seller's historical "
              "on-time rate.\n")

    sub = df.dropna(subset=["review_score", "is_late"])
    grp = sub.groupby("is_late")["review_score"].agg(["mean", "median", "count"])
    rel = save_table(grp.reset_index(), "review_score_by_lateness")
    report.table_ref("Mean/median review_score, on-time vs. late", rel)

    bad_rate_by_late = sub.groupby("is_late")["bad_review"].mean() * 100
    for is_late_val, rate in bad_rate_by_late.items():
        label = "late" if is_late_val else "on-time"
        report.p(f"- bad_review rate when {label}: {rate:.2f}%")

    # Contribution share: lateness can be high-risk per order while still
    # explaining only a minority of all bad reviews.
    bad_counts_by_late = sub.groupby("is_late")["bad_review"].sum()
    total_bad = bad_counts_by_late.sum()
    n_by_late = sub.groupby("is_late").size()
    if total_bad > 0:
        report.p("\nShare of all bad reviews:\n")
        for is_late_val in [False, True]:
            if is_late_val not in bad_counts_by_late.index:
                continue
            label = "late" if is_late_val else "on-time"
            count = bad_counts_by_late.loc[is_late_val]
            share = count / total_bad * 100
            report.p(f"- {label} orders: {int(count):,} bad reviews out of {int(n_by_late.loc[is_late_val]):,} orders "
                      f"({share:.1f}% of all bad reviews)")

    corr_sub = df.dropna(subset=["days_late", "review_score"])
    if len(corr_sub) > 10:
        corr = corr_sub["days_late"].corr(corr_sub["review_score"])
        report.p(f"\n- Pearson correlation(days_late, review_score) = {corr:.3f} (n={len(corr_sub):,})")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    sub.boxplot(column="review_score", by="is_late", ax=ax)
    ax.set_xlabel("is_late")
    ax.set_ylabel("review_score")
    ax.set_title("Review score by lateness")
    plt.suptitle("")
    rel = savefig(fig, "review_score_by_lateness_box")
    report.fig_ref("Review score by lateness (boxplot)", rel)

    canc = df[df["is_canceled_or_unavailable"]]
    report.p(f"\n- Of {len(canc):,} canceled/unavailable orders, {canc['review_score'].notna().sum():,} "
              f"have a review score (mean {canc['review_score'].mean():.2f} where present).")


def section_seller_variance(df, raw, report: Report):
    """Check whether bad reviews are concentrated among sellers."""
    report.h2("4. Seller-level variance")
    report.p("**Attribution caveat:** for multi-seller orders, the order's single review is "
              "assigned to every seller on that order. The data does not show which seller caused "
              "the issue. This affects about 2% of orders.\n")

    seller_stats = build_seller_level_table(raw, df)
    MIN_ORDERS = 10
    qualified = seller_stats[seller_stats["n_orders"] >= MIN_ORDERS].copy()

    report.p(f"- Total sellers: {len(seller_stats):,}")
    report.p(f"- Sellers with >= {MIN_ORDERS} orders (used below for rate stability): {len(qualified):,} "
              f"({len(qualified)/len(seller_stats)*100:.1f}% of sellers, "
              f"{qualified['n_orders'].sum()/seller_stats['n_orders'].sum()*100:.1f}% of order volume)")

    rel = save_table(
        qualified.sort_values("bad_review_rate", ascending=False).head(20),
        "worst_20_sellers"
    )
    report.table_ref(f"Worst 20 sellers by bad_review_rate (n_orders>={MIN_ORDERS})", rel)

    # Use the same spread metric as later sections so the results can be compared.
    if len(qualified) > 0:
        spread = qualified["bad_review_rate"].max() - qualified["bad_review_rate"].min()
        report.p(f"\n- Seller bad-review-rate spread (min-max, n_orders>={MIN_ORDERS}): {spread*100:.1f} pp "
                  f"across {len(qualified):,} qualifying sellers")
        weighted_std_val = weighted_std(qualified["bad_review_rate"].values, qualified["n_orders"].values)
        report.p(f"- Volume-weighted std of seller bad-review rate: {weighted_std_val*100:.2f} pp. "
                  "This can be compared with the category and product figures below.")

    # Concentration: how much of the bad-review volume comes from the riskiest sellers?
    if len(qualified) >= 10:
        q_sorted = qualified.sort_values("bad_review_rate", ascending=False).reset_index(drop=True)
        total_bad_qualified = q_sorted["bad_review_count"].sum()
        decile_cut = max(1, len(q_sorted) // 10)
        worst_decile_bad = q_sorted.iloc[:decile_cut]["bad_review_count"].sum()
        worst_decile_orders = q_sorted.iloc[:decile_cut]["n_orders"].sum()
        share_of_bad = worst_decile_bad / total_bad_qualified * 100 if total_bad_qualified > 0 else float("nan")
        share_of_orders = worst_decile_orders / q_sorted["n_orders"].sum() * 100
        report.p(f"\n- Worst decile of qualifying sellers ({decile_cut} sellers, {share_of_orders:.1f}% of "
                  f"qualifying order volume) account for {share_of_bad:.1f}% of bad reviews among "
                  "qualifying sellers. If this share is well above their order share, seller risk "
                  "ranking is likely useful.")

    # Check whether larger or more experienced sellers have lower bad-review rates.
    if len(qualified) > 10:
        corr = qualified["n_orders"].corr(qualified["bad_review_rate"])
        report.p(f"\n- Correlation(seller order volume, bad_review_rate) = {corr:.3f} among qualifying "
                  "sellers. A negative value would mean higher-volume sellers tend to be more reliable.")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    qualified["bad_review_rate"].hist(bins=30, ax=ax, color="#8172B2")
    ax.set_xlabel("bad_review_rate")
    ax.set_title(f"Seller bad_review_rate distribution (n_orders>={MIN_ORDERS})")
    rel = savefig(fig, "seller_bad_review_rate_distribution")
    report.fig_ref("Distribution of seller-level bad_review_rate", rel)

    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.scatter(qualified["n_orders"], qualified["bad_review_rate"], alpha=0.4, s=15, color="#4C72B0")
    ax.set_xscale("log")
    ax.set_xlabel("seller n_orders (log scale)")
    ax.set_ylabel("bad_review_rate")
    ax.set_title("Seller volume vs. bad_review_rate")
    rel = savefig(fig, "seller_volume_vs_bad_review_rate")
    report.fig_ref("Seller order volume vs. bad_review_rate (scatter)", rel)


def section_category_variance(df, report: Report):
    """Check whether product category separates good and bad outcomes."""
    report.h2("5. Product category variance")

    cat_stats = grouped_bad_review_rate(df, "primary_category", min_orders=30)

    rel = save_table(cat_stats.reset_index(), "category_bad_review_rates")
    report.table_ref("bad_review rate by product category (n_orders>=30), sorted worst-first", rel)

    report.p(f"\n- Categories analysed: {len(cat_stats)} (after filtering n_orders>=30)")
    if len(cat_stats) > 0:
        report.p(f"- Worst category: `{cat_stats.index[0]}` ({cat_stats['bad_review_rate'].iloc[0]*100:.1f}%, "
                  f"n={cat_stats['n_orders'].iloc[0]})")
        report.p(f"- Best category: `{cat_stats.index[-1]}` ({cat_stats['bad_review_rate'].iloc[-1]*100:.1f}%, "
                  f"n={cat_stats['n_orders'].iloc[-1]})")
        spread = cat_stats["bad_review_rate"].max() - cat_stats["bad_review_rate"].min()
        report.p(f"- Spread (max-min bad_review_rate across categories): {spread*100:.1f} pp. "
                  "Min-max can be sensitive to smaller categories, so the weighted-std number below "
                  "is better for comparison.")
        cat_weighted_std = weighted_std(cat_stats["bad_review_rate"].values, cat_stats["n_orders"].values)
        report.p(f"- Volume-weighted std of category bad_review_rate: {cat_weighted_std*100:.2f} pp "
                  "(same method as the seller and product sections).")

    fig, ax = plt.subplots(figsize=(6, 8))
    top = pd.concat([cat_stats.head(10), cat_stats.tail(10)])
    top["bad_review_rate"].sort_values().plot(kind="barh", ax=ax, color="#55A868")
    ax.set_xlabel("bad_review rate")
    ax.set_title("Best 10 / worst 10 categories (n>=30)")
    rel = savefig(fig, "category_bad_review_rates")
    report.fig_ref("Best/worst categories by bad_review rate", rel)


def section_price_freight(df, report: Report):
    """Compare price, freight, installments, and payment type by outcome."""
    report.h2("6. Price, freight, and payment structure")

    sub = df.dropna(subset=["bad_review"])
    for col in ["total_item_price", "total_freight_value", "max_installments"]:
        if col not in sub.columns:
            continue
        grp = sub.groupby("bad_review")[col].median()
        report.p(f"- Median `{col}`: bad_review=False -> {grp.get(False, float('nan')):.2f}, "
                  f"bad_review=True -> {grp.get(True, float('nan')):.2f}")

    fig, axes = plt.subplots(1, 2, figsize=(9, 3.5))
    sub.boxplot(column="total_item_price", by="bad_review", ax=axes[0])
    axes[0].set_ylim(0, sub["total_item_price"].quantile(0.95))
    axes[0].set_title("total_item_price")
    sub.boxplot(column="total_freight_value", by="bad_review", ax=axes[1])
    axes[1].set_ylim(0, sub["total_freight_value"].quantile(0.95))
    axes[1].set_title("total_freight_value")
    plt.suptitle("")
    fig.tight_layout()
    rel = savefig(fig, "price_freight_by_bad_review")
    report.fig_ref("Price/freight distributions by bad_review (clipped at p95)", rel)

    pay_stats = sub.groupby("primary_payment_type")["bad_review"].agg(["mean", "count"]).sort_values("mean", ascending=False)
    rel = save_table(pay_stats.reset_index(), "bad_review_by_payment_type")
    report.table_ref("bad_review rate by primary payment type", rel)


def section_distance(df, report: Report):
    """Check whether customer-seller distance is useful for prediction."""
    report.h2("7. Customer-seller distance")
    report.p("Distance is measured between the customer's zip centroid and the primary seller's "
              "zip centroid. For multi-seller orders, this is an approximation.\n")

    n_missing = df["customer_seller_distance_km"].isna().sum()
    report.p(f"- Orders with a computed distance: {len(df) - n_missing:,} / {len(df):,} "
              f"({(len(df)-n_missing)/len(df)*100:.1f}%)")

    sub = df.dropna(subset=["customer_seller_distance_km", "bad_review"])
    if len(sub) > 10:
        med = sub.groupby("bad_review")["customer_seller_distance_km"].median()
        report.p(f"- Median distance (km): bad_review=False -> {med.get(False, float('nan')):.1f}, "
                  f"bad_review=True -> {med.get(True, float('nan')):.1f}")
        corr = sub["customer_seller_distance_km"].corr(sub["bad_review"].astype(float))
        report.p(f"- Correlation(distance_km, bad_review) = {corr:.3f} (n={len(sub):,})")

        # distance is a plausible proxy for delivery lateness risk -- check
        late_sub = df.dropna(subset=["customer_seller_distance_km", "is_late"])
        if len(late_sub) > 10:
            corr_late = late_sub["customer_seller_distance_km"].corr(late_sub["is_late"].astype(float))
            report.p(f"- Correlation(distance_km, is_late) = {corr_late:.3f} (n={len(late_sub):,}). "
                      "Distance is known at order time, so it could be useful if it explains lateness.")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    sub.boxplot(column="customer_seller_distance_km", by="bad_review", ax=ax)
    ax.set_ylim(0, sub["customer_seller_distance_km"].quantile(0.95) if len(sub) > 0 else 1)
    ax.set_title("Distance by bad_review")
    plt.suptitle("")
    rel = savefig(fig, "distance_by_bad_review")
    report.fig_ref("Customer-seller distance by bad_review (clipped at p95)", rel)


def section_time_trends(df, report: Report):
    """Check whether bad-review rates drift over time."""
    report.h2("8. Time trends")

    sub = df.dropna(subset=["order_purchase_timestamp", "bad_review"]).copy()
    sub["purchase_month"] = sub["order_purchase_timestamp"].dt.to_period("M").astype(str)
    monthly = sub.groupby("purchase_month").agg(
        n_orders=("order_id", "count"),
        bad_review_rate=("bad_review", "mean"),
    )
    monthly = monthly[monthly["n_orders"] > 500]  # Exclude partial months at the dataset edges.
    rel = save_table(monthly.reset_index(), "monthly_bad_review_rate")
    report.table_ref("Monthly order volume and bad_review rate", rel)

    fig, ax1 = plt.subplots(figsize=(8, 3.5))
    ax2 = ax1.twinx()
    monthly["n_orders"].plot(ax=ax1, color="#4C72B0", label="n_orders")
    monthly["bad_review_rate"].plot(ax=ax2, color="#C44E52", label="bad_review_rate")
    ax1.set_ylabel("n_orders", color="#4C72B0")
    ax2.set_ylabel("bad_review_rate", color="#C44E52")
    ax1.set_xlabel("purchase month")
    ax1.set_title("Monthly volume vs. bad_review rate")
    fig.autofmt_xdate(rotation=45)
    rel = savefig(fig, "monthly_trend")
    report.fig_ref("Monthly volume and bad_review rate", rel)


def section_product_variance(df, raw, report: Report):
    """Check whether specific products add signal beyond category."""
    report.h2("9. Product-level concentration")
    report.p("This repeats the seller-level analysis for individual products. The question is "
              "whether specific products show sharper risk than their broader category.\n")

    product_stats = build_product_level_table(raw, df)
    MIN_ORDERS = 10
    qualified = product_stats[product_stats["n_orders"] >= MIN_ORDERS].copy()

    report.p(f"- Total distinct products: {len(product_stats):,}")
    report.p(f"- Products with >= {MIN_ORDERS} orders: {len(qualified):,} "
              f"({len(qualified)/len(product_stats)*100:.1f}% of products, "
              f"{qualified['n_orders'].sum()/product_stats['n_orders'].sum()*100:.1f}% of order volume) "
              "-- most products sell too rarely for a stable per-product rate.")

    if len(qualified) > 0:
        rel = save_table(qualified.sort_values("bad_review_rate", ascending=False).head(20), "worst_20_products")
        report.table_ref(f"Worst 20 products by bad_review_rate (n_orders>={MIN_ORDERS})", rel)

        p_weighted_std = weighted_std(qualified["bad_review_rate"].values, qualified["n_orders"].values)
        report.p(f"\n- Volume-weighted std of product bad_review_rate: {p_weighted_std*100:.2f} pp. "
                  "Compare this with the seller and category figures. A larger product value means "
                  "category averages are hiding sharper product-level problems.")

        q_sorted = qualified.sort_values("bad_review_rate", ascending=False).reset_index(drop=True)
        total_bad = q_sorted["bad_review_count"].sum()
        decile_cut = max(1, len(q_sorted) // 10)
        worst_decile_bad = q_sorted.iloc[:decile_cut]["bad_review_count"].sum()
        worst_decile_orders = q_sorted.iloc[:decile_cut]["n_orders"].sum()
        if total_bad > 0:
            report.p(f"- Worst decile of qualifying products ({decile_cut} products, "
                      f"{worst_decile_orders/q_sorted['n_orders'].sum()*100:.1f}% of qualifying volume) "
                      f"account for {worst_decile_bad/total_bad*100:.1f}% of bad reviews among qualifying products.")


def section_geography(df, report: Report):
    """Check whether location patterns matter beyond raw distance."""
    report.h2("10. Geographic patterns (buyer and seller location)")
    report.p("This section looks at customer and seller regions. It is separate from physical "
              "distance: two orders can travel similar distances but pass through different regions.\n")

    # customer state
    cust_state = grouped_bad_review_rate(df, "customer_state", min_orders=30)
    rel = save_table(cust_state.reset_index(), "bad_review_by_customer_state")
    report.table_ref("bad_review rate by customer_state (n_orders>=30)", rel)
    if len(cust_state) > 0:
        cust_wstd = weighted_std(cust_state["bad_review_rate"].values, cust_state["n_orders"].values)
        report.p(f"- Customer state: worst=`{cust_state.index[0]}` ({cust_state['bad_review_rate'].iloc[0]*100:.1f}%), "
                  f"best=`{cust_state.index[-1]}` ({cust_state['bad_review_rate'].iloc[-1]*100:.1f}%), "
                  f"volume-weighted std={cust_wstd*100:.2f} pp")

    # seller state
    sell_state = grouped_bad_review_rate(df, "seller_state", min_orders=30)
    rel = save_table(sell_state.reset_index(), "bad_review_by_seller_state")
    report.table_ref("bad_review rate by seller_state (n_orders>=30)", rel)
    if len(sell_state) > 0:
        sell_wstd = weighted_std(sell_state["bad_review_rate"].values, sell_state["n_orders"].values)
        report.p(f"- Seller state: worst=`{sell_state.index[0]}` ({sell_state['bad_review_rate'].iloc[0]*100:.1f}%), "
                  f"best=`{sell_state.index[-1]}` ({sell_state['bad_review_rate'].iloc[-1]*100:.1f}%), "
                  f"volume-weighted std={sell_wstd*100:.2f} pp. Compare this with customer state "
                  "and the other grouping-level signals.")

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    cust_state["bad_review_rate"].sort_values().plot(kind="barh", ax=axes[0], color="#4C72B0")
    axes[0].set_title("bad_review rate by customer_state")
    sell_state["bad_review_rate"].sort_values().plot(kind="barh", ax=axes[1], color="#DD8452")
    axes[1].set_title("bad_review rate by seller_state")
    fig.tight_layout()
    rel = savefig(fig, "bad_review_by_state")
    report.fig_ref("bad_review rate by customer_state / seller_state", rel)

    # top cities (higher small-n noise risk, flagged explicitly)
    for label, col, fname in [
        ("customer_city", "customer_city", "bad_review_by_customer_city"),
        ("seller_city", "seller_city", "bad_review_by_seller_city"),
    ]:
        city_stats = grouped_bad_review_rate(df, col, min_orders=50)
        rel = save_table(city_stats.reset_index(), fname)
        report.table_ref(f"bad_review rate by {label} (n_orders>=50; still noisier than state-level cuts)", rel)

    # lane analysis: customer_state x seller_state
    lane = df.dropna(subset=["customer_state", "seller_state", "bad_review"])
    lane_stats = lane.groupby(["seller_state", "customer_state"]).agg(
        n_orders=("order_id", "count"), bad_review_rate=("bad_review", "mean"),
        avg_distance_km=("customer_seller_distance_km", "mean"),
    ).query("n_orders >= 50").sort_values("bad_review_rate", ascending=False)
    rel = save_table(lane_stats.reset_index(), "bad_review_by_lane")
    report.table_ref("bad_review rate by seller_state->customer_state lane (n_orders>=50), worst-first", rel)
    if len(lane_stats) > 0:
        overall_rate = df["bad_review"].mean()
        # Keep column access separate so nullable pandas dtypes do not turn a
        # missing distance into the literal string "<NA>" in the report.
        worst_seller_state, worst_customer_state = lane_stats.index[0]
        worst_rate = float(lane_stats["bad_review_rate"].iloc[0])
        worst_n = int(lane_stats["n_orders"].iloc[0])
        worst_dist = lane_stats["avg_distance_km"].iloc[0]
        dist_str = f"{worst_dist:.0f}km" if pd.notna(worst_dist) else "unknown (no geolocation match for this lane)"
        report.p(f"\n- Worst lane: `{worst_seller_state}` -> `{worst_customer_state}` "
                  f"({worst_rate*100:.1f}% vs. {overall_rate*100:.1f}% overall, "
                  f"n={worst_n}, avg distance {dist_str}) -- "
                  "compare this with the weak distance correlation in section 7 before treating it "
                  "as a true route effect.")


def section_business_impact(df, report: Report):
    """Estimate order value at risk and check simple repeat-purchase patterns."""
    report.h2("11. Business impact: revenue at risk and repurchase")
    report.p("This section translates the patterns into rough R$ terms. These are descriptive "
              "numbers, not causal estimates.\n")

    # revenue at risk
    sub = df.dropna(subset=["bad_review", "order_value"])
    total_value = sub["order_value"].sum()
    bad_value = sub.loc[sub["bad_review"].astype(bool), "order_value"].sum()
    report.p(f"- Total order value (reviewed orders): R$ {total_value:,.0f}")
    report.p(f"- Order value sitting in bad_review orders: R$ {bad_value:,.0f} "
              f"({bad_value/total_value*100:.1f}% of total order value, vs. "
              f"{sub['bad_review'].mean()*100:.1f}% of orders by count -- "
              f"{'higher' if bad_value/total_value > sub['bad_review'].mean() else 'lower'} share of "
              "value than count, so bad reviews skew toward "
              f"{'higher' if bad_value/total_value > sub['bad_review'].mean() else 'lower'}-value orders)")

    # repurchase / churn analysis using customer_unique_id
    report.p("\n**Repurchase analysis** uses `customer_unique_id` to link repeat orders from the "
              "same customer.\n")

    cust = df.dropna(subset=["customer_unique_id", "order_purchase_timestamp"]).copy()
    max_date = cust["order_purchase_timestamp"].max()
    censor_cutoff = max_date - pd.Timedelta(days=180)

    first_orders = (
        cust.sort_values("order_purchase_timestamp")
        .groupby("customer_unique_id")
        .first()
        .reset_index()
    )
    order_counts = cust.groupby("customer_unique_id")["order_id"].nunique().rename("n_orders_total")
    first_orders = first_orders.merge(order_counts, on="customer_unique_id", how="left")
    first_orders["repurchased"] = first_orders["n_orders_total"] > 1

    # downstream (post-first-order) revenue per customer, 0 for non-repurchasers
    downstream_value = (
        cust.sort_values("order_purchase_timestamp")
        .groupby("customer_unique_id")
        .apply(lambda g: g["order_value"].iloc[1:].sum() if len(g) > 1 else 0.0, include_groups=False)
        .rename("downstream_value")
    )
    first_orders = first_orders.merge(downstream_value, on="customer_unique_id", how="left")

    eligible = first_orders[
        (first_orders["order_purchase_timestamp"] <= censor_cutoff) & first_orders["bad_review"].notna()
    ]
    report.p(f"- Customers eligible for this analysis (first order at least 180 days before the "
              f"dataset's last order, and first order was reviewed): "
              f"{len(eligible):,} / {len(first_orders):,}")

    if len(eligible) > 20:
        grp = eligible.groupby(eligible["bad_review"].astype(bool)).agg(
            n_customers=("customer_unique_id", "count"),
            repurchase_rate=("repurchased", "mean"),
            avg_downstream_value=("downstream_value", "mean"),
        )
        rel = save_table(grp.reset_index(), "repurchase_by_first_order_outcome")
        report.table_ref("Repurchase rate and avg. downstream value, by first-order bad_review status", rel)

        if True in grp.index and False in grp.index:
            rr_good = grp.loc[False, "repurchase_rate"]
            rr_bad = grp.loc[True, "repurchase_rate"]
            dv_good = grp.loc[False, "avg_downstream_value"]
            dv_bad = grp.loc[True, "avg_downstream_value"]
            report.p(f"\n- Repurchase rate after a GOOD first order: {rr_good*100:.2f}%")
            report.p(f"- Repurchase rate after a BAD first order: {rr_bad*100:.2f}%")
            report.p(f"- Avg. downstream order value per customer, good first order: R$ {dv_good:.2f}")
            report.p(f"- Avg. downstream order value per customer, bad first order: R$ {dv_bad:.2f}")
            gap = dv_good - dv_bad
            n_bad_total = int(sub["bad_review"].astype(bool).sum())
            rough_estimate = gap * n_bad_total
            direction = "lower" if gap > 0 else "higher"
            report.p(f"\n- **Rough estimate:** customers whose first order was bad had "
                      f"R$ {abs(gap):.2f} {direction} average downstream order value than customers "
                      f"whose first order was good. Applying that gap to all "
                      f"{n_bad_total:,} bad-review orders in the full dataset (not just the eligible "
                      f"subset) gives an illustrative figure of **R$ {abs(rough_estimate):,.0f}** in "
                      f"associated downstream revenue {'at risk' if gap > 0 else '(no apparent downside found in this data)'}. "
                      "**This is not causal.** Customers who leave bad reviews may differ from other "
                      "customers for many reasons, such as product mix or one-off purchases. Treat this "
                      "as a prompt for a better churn study, not as a business-case number.")
    else:
        report.p("- Not enough eligible customers in this run to report repurchase stats reliably.")


PT_STOPWORDS = set("""
a as o os um uma uns umas de da do das dos em no na nos nas para por com sem
que quem qual quais e ou mas se nao não muito mais menos ja já ainda so só
foi ser estar tem tem tinha era sao são eu tu ele ela nos vos eles elas meu
minha teu tua seu sua nosso nossa este esta esse essa aquele aquela isto
isso aquilo ao aos à às pelo pela pelos pelas num numa entre até após como
quando onde porque pois todo toda todos todas outro outra outros outras
me te lhe lhes nos vos ja mesmo mesma sobre depois antes
""".split())


def section_qualitative_text(df, report: Report):
    """Inspect text for bad reviews that were not late."""
    report.h2("12. Qualitative signal: what do bad-but-on-time reviews say?")
    report.p("Section 3 showed that many bad reviews happen on orders that arrived on time. "
              "`review_comment_message` cannot be a model feature because it is written after the "
              "outcome, but it can explain what the structured columns miss. This section provides "
              "a word-frequency table and a fixed sample for manual reading.\n")

    target = df[
        (df["bad_review"].fillna(False).astype(bool)) &
        (df["is_late"].fillna(False).astype(bool) == False) &  # noqa: E712 -- explicit re: nullable bool
        (df["review_comment_message"].notna())
    ].copy()
    report.p(f"- Bad-review, on-time (or unknown-lateness), with a comment: {len(target):,} orders")

    if len(target) > 0:
        # word frequency (reproducible, quantitative)
        import re
        from collections import Counter
        counter = Counter()
        for msg in target["review_comment_message"].astype(str):
            tokens = re.findall(r"[a-zà-ú]+", msg.lower())
            for t in tokens:
                if len(t) >= 3 and t not in PT_STOPWORDS:
                    counter[t] += 1
        top_words = pd.DataFrame(counter.most_common(30), columns=["word", "count"])
        rel = save_table(top_words, "bad_ontime_review_word_frequency")
        report.table_ref("Top 30 words in bad-review/on-time comments (Portuguese stopwords removed)", rel)

        # fixed random sample for manual reading
        sample_cols = ["order_id", "review_score", "primary_category", "order_value",
                        "review_comment_title", "review_comment_message"]
        sample = target[sample_cols].sample(n=min(40, len(target)), random_state=42)
        rel = save_table(sample, "bad_ontime_review_sample")
        report.table_ref("Fixed random sample (n<=40, seed=42) of bad-review/on-time comments for manual reading", rel)
        report.p("\n**Note:** the sample and word list are in Portuguese, the original review "
                  "language. A fluent read is better than relying only on machine translation, because "
                  "small wording differences can explain the complaint.")


def section_review_categories(df, report: Report):
    """Join LLM complaint categories back to orders for clearer counts."""
    report.h2("13. LLM-categorized complaint reasons")

    if not NLP_CATEGORIES_PATH.exists():
        report.p(f"- `{NLP_CATEGORIES_PATH.relative_to(OUTPUT_DIR.parent)}` not found -- "
                  "`src/nlp/categorize_reviews.py` is a separate manual stage that needs "
                  "OPENROUTER_API_KEY. Skipping this section.")
        return

    cats = pd.read_csv(NLP_CATEGORIES_PATH, usecols=["order_id", "category_id", "category_name"])
    report.p(f"- Loaded {len(cats):,} categorized reviews from `{NLP_CATEGORIES_PATH.name}` "
              f"(model: `google/gemini-2.5-flash`; see `output/nlp/summary.md` for category "
              "definitions and example comments).\n")

    merged = cats.merge(
        df[["order_id", "is_late", "primary_category", "order_value", "customer_state"]],
        on="order_id", how="left",
    )

    n_bad_total = int(df["bad_review"].fillna(False).astype(bool).sum())
    n_bad_with_comment = int((df["bad_review"].fillna(False).astype(bool) & df["review_comment_message"].notna()).sum())
    report.p(f"- Coverage: {len(cats):,} / {n_bad_total:,} bad reviews ({len(cats)/n_bad_total*100:.1f}%) "
              f"have a non-empty comment and got categorized; the remaining "
              f"{n_bad_total - n_bad_with_comment:,} bad reviews have no comment text at all and are "
              "not visible to this text analysis.")

    # Use labeled categories to explain the on-time bad-review segment.
    known_lateness = merged.dropna(subset=["is_late"]).copy()
    known_lateness["is_late"] = known_lateness["is_late"].astype(bool)
    on_time = known_lateness[~known_lateness["is_late"]]
    late = known_lateness[known_lateness["is_late"]]
    if len(on_time) > 20:
        on_time_dist = (on_time["category_name"].value_counts(normalize=True) * 100).round(1)
        late_dist = (late["category_name"].value_counts(normalize=True) * 100).round(1)
        cmp_table = pd.DataFrame({"on_time_pct": on_time_dist, "late_pct": late_dist}).fillna(0.0)
        cmp_table["on_time_n"] = on_time["category_name"].value_counts()
        cmp_table["late_n"] = late["category_name"].value_counts()
        cmp_table = cmp_table.sort_values("on_time_pct", ascending=False)
        rel = save_table(cmp_table.reset_index().rename(columns={"index": "category_name"}),
                          "complaint_category_by_lateness")
        report.table_ref("Complaint category share, on-time vs. late bad reviews", rel)

        top_on_time = cmp_table.index[0]
        report.p(f"\n- Among on-time bad reviews with a comment (n={len(on_time):,}), the top category is "
                  f"`{top_on_time}` ({cmp_table.loc[top_on_time, 'on_time_pct']:.1f}%) -- this is the "
                  "clearest labeled explanation for the on-time bad-review segment.")

    # Compare the LLM's delivery complaint label with the structured late flag.
    late_label = merged[merged["category_name"] == "Late Delivery or Non-Delivery"]
    late_label_known = late_label.dropna(subset=["is_late"])
    if len(late_label_known) > 20:
        agree_rate = late_label_known["is_late"].astype(bool).mean() * 100
        report.p(f"\n- **Validation check:** of {len(late_label_known):,} reviews the LLM labeled "
                  f"`Late Delivery or Non-Delivery` (with a known delivery outcome), "
                  f"{agree_rate:.1f}% were actually late by the structured `is_late` field "
                  f"(delivered after `order_estimated_delivery_date`). The gap shows that `is_late` "
                  "does not capture every delivery-related complaint.")

    # Check whether product categories have different complaint mixes.
    cat_counts = merged.groupby("primary_category").size()
    qualified_cats = cat_counts[cat_counts >= 30].index
    sub = merged[merged["primary_category"].isin(qualified_cats)]
    if len(sub) > 0:
        contingency = (
            pd.crosstab(sub["primary_category"], sub["category_name"], normalize="index") * 100
        ).round(1)
        rel = save_table(contingency.reset_index(), "complaint_category_by_product_category")
        report.table_ref(
            "Complaint category mix (%) by product category (primary_category, n_orders>=30 within "
            "this categorized subset)",
            rel,
        )
        for label, col in [("Damaged or Broken Product", "Damaged or Broken Product"),
                            ("Wrong Item Delivered / Product Divergence", "Wrong Item Delivered / Product Divergence")]:
            if col in contingency.columns:
                top3 = contingency[col].sort_values(ascending=False).head(3)
                report.p(f"\n- Product categories with the highest `{label}` share: " +
                          ", ".join(f"`{idx}` ({val:.1f}%)" for idx, val in top3.items()))

    # Compare median order value by complaint category.
    val_by_cat = merged.dropna(subset=["order_value"]).groupby("category_name")["order_value"].median().sort_values(ascending=False)
    if len(val_by_cat) > 0:
        rel = save_table(val_by_cat.rename("median_order_value").reset_index(), "complaint_category_median_order_value")
        report.table_ref("Median order value by complaint category", rel)
        report.p(f"\n- Highest median order value: `{val_by_cat.index[0]}` (R$ {val_by_cat.iloc[0]:.2f}); "
                  f"lowest: `{val_by_cat.index[-1]}` (R$ {val_by_cat.iloc[-1]:.2f}).")

    fig, ax = plt.subplots(figsize=(6, 4))
    overall_dist = merged["category_name"].value_counts(normalize=True).sort_values() * 100
    overall_dist.plot(kind="barh", ax=ax, color="#C44E52")
    ax.set_xlabel("% of categorized bad reviews")
    ax.set_title("Complaint category distribution")
    rel = savefig(fig, "complaint_category_distribution")
    report.fig_ref("Complaint category distribution (all categorized bad reviews)", rel)

    report.p("\n**Future work:** these labels are post-outcome text, so they cannot be used as "
              "before-the-fact model features. They are still useful for Ops. First, they can help "
              "route complaints to the right team, such as logistics, product QA, fraud, or support. "
              "Second, complaint mix can become a seller/product quality signal over time. For "
              "example, a rising share of `Wrong Item Delivered` complaints points to a different "
              "problem than a rising share of `Late Delivery` complaints. To use this regularly, the "
              "categorization step should be folded into the pipeline and expanded beyond the "
              f"{len(cats)/n_bad_total*100:.0f}% of bad reviews that contain comment text.")


def main():
    print("[eda] Loading raw tables...")
    raw = load_raw(RAW_DIR)

    print("[eda] Building order-level table...")
    df = build_order_level_table(raw)
    print(f"[eda] Order-level table: {df.shape[0]:,} rows x {df.shape[1]} cols")

    report = Report()

    print("[eda] Section 1: data quality...")
    section_data_quality(raw, df, report)

    print("[eda] Section 2: target candidates...")
    section_target_candidates(df, report)

    print("[eda] Section 3: target overlap...")
    section_target_overlap(df, report)

    print("[eda] Section 4: seller variance...")
    section_seller_variance(df, raw, report)

    print("[eda] Section 5: category variance...")
    section_category_variance(df, report)

    print("[eda] Section 6: price/freight/payment...")
    section_price_freight(df, report)

    print("[eda] Section 7: distance (partial)...")
    section_distance(df, report)

    print("[eda] Section 8: time trends...")
    section_time_trends(df, report)

    print("[eda] Section 9: product variance...")
    section_product_variance(df, raw, report)

    print("[eda] Section 10: geography...")
    section_geography(df, report)

    print("[eda] Section 11: business impact...")
    section_business_impact(df, report)

    print("[eda] Section 12: qualitative text...")
    section_qualitative_text(df, report)

    print("[eda] Section 13: LLM-categorized complaint reasons...")
    section_review_categories(df, report)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    report.write(OUTPUT_DIR / "summary.md")
    print(f"\n[eda] Done. See {OUTPUT_DIR / 'summary.md'} and {FIG_DIR}/ and {TABLE_DIR}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
