"""
EDA stage: investigates the target-definition candidates and driver
variables laid out in docs/problem_framing.md.

Run:
    python -m src.eda.run_eda

Outputs (all under output/eda/):
    summary.md          human-readable findings, numbers inline
    tables/*.csv         supporting aggregated tables
    figures/*.png        supporting plots

Design intent: this script produces PLAIN NUMBERS AND PLOTS, not
conclusions -- interpretation happens in docs/problem_framing.md (revised
after reading this output) and eventually README.md. Keeping the split
this way makes it easy to see what's a measured fact vs. a judgment call.
"""

import sys
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.data.loader import RAW_DIR, load_raw, build_order_level_table, build_seller_level_table

warnings.filterwarnings("ignore")

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output" / "eda"
FIG_DIR = OUTPUT_DIR / "figures"
TABLE_DIR = OUTPUT_DIR / "tables"

plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.3


def savefig(fig, name):
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    path = FIG_DIR / f"{name}.png"
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    return path.relative_to(OUTPUT_DIR)


def save_table(df, name):
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    path = TABLE_DIR / f"{name}.csv"
    df.to_csv(path, index=False)
    return path.relative_to(OUTPUT_DIR)


class Report:
    """Accumulates markdown sections in order, written out at the end."""
    def __init__(self):
        self.lines = ["# EDA Summary\n", "Auto-generated by `src/eda/run_eda.py`. Do not hand-edit.\n"]

    def h2(self, text):
        self.lines.append(f"\n## {text}\n")

    def p(self, text):
        self.lines.append(f"{text}\n")

    def table_ref(self, caption, rel_path):
        self.lines.append(f"\n*{caption}* -> `{rel_path}`\n")

    def fig_ref(self, caption, rel_path):
        self.lines.append(f"\n*{caption}* -> `{rel_path}`\n")

    def write(self, path):
        path.write_text("\n".join(self.lines))


# ---------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------

def section_data_quality(raw, df, report: Report):
    report.h2("1. Data quality checks")

    n_orders = len(df)
    report.p(f"- Total orders: {n_orders:,}")

    status_counts = df["order_status"].value_counts()
    rel = save_table(status_counts.rename("count").reset_index().rename(columns={"index": "order_status"}),
                      "order_status_counts")
    report.table_ref("Order status counts", rel)

    key_cols = [
        "primary_category", "total_item_price", "total_freight_value",
        "primary_payment_type", "max_installments", "customer_lat", "customer_lng",
        "n_distinct_sellers",
    ]
    missing = df[key_cols].isna().mean().sort_values(ascending=False) * 100
    report.p("\nMissingness (%) among candidate pre-outcome features:\n")
    for col, pct in missing.items():
        report.p(f"- `{col}`: {pct:.2f}%")

    n_missing_geo = df["customer_lat"].isna().sum()
    report.p(f"\n- Customer zip prefixes with no geolocation match: {n_missing_geo:,} ({n_missing_geo/n_orders*100:.2f}%)")

    n_zero_installments = (raw["order_payments"]["payment_installments"] == 0).sum()
    report.p(f"- Payment rows with `payment_installments == 0`: {n_zero_installments:,} "
             f"({n_zero_installments/len(raw['order_payments'])*100:.3f}% of payment rows) -- check payment_type for these.")
    if n_zero_installments > 0:
        zero_inst_types = raw["order_payments"].loc[
            raw["order_payments"]["payment_installments"] == 0, "payment_type"
        ].value_counts()
        rel = save_table(zero_inst_types.rename("count").reset_index().rename(columns={"index": "payment_type"}),
                          "zero_installment_payment_types")
        report.table_ref("Payment types among 0-installment rows", rel)

    geo = raw["geolocation"]
    n_dupe = geo.duplicated().sum()
    report.p(f"\n- Geolocation table: {len(geo):,} rows, {n_dupe:,} exact duplicates ({n_dupe/len(geo)*100:.1f}%), "
             f"collapsed to zip-prefix centroids for the `customer_lat`/`customer_lng` features used below.")


def section_target_candidates(df, report: Report):
    report.h2("2. Target candidate distributions")

    review_dist = df["review_score"].value_counts(dropna=False).sort_index()
    rel = save_table(review_dist.rename("count").reset_index().rename(columns={"index": "review_score"}),
                      "review_score_distribution")
    report.table_ref("Review score distribution (including NaN = no review)", rel)

    n_reviewed = df["review_score"].notna().sum()
    bad_review_rate = df["bad_review"].mean()
    report.p(f"- Orders with a review score: {n_reviewed:,} / {len(df):,} ({n_reviewed/len(df)*100:.1f}%)")
    report.p(f"- `bad_review` (score<=2) rate among reviewed orders: {bad_review_rate*100:.2f}%")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    review_dist.dropna().plot(kind="bar", ax=ax, color="#4C72B0")
    ax.set_xlabel("review_score")
    ax.set_ylabel("count")
    ax.set_title("Review score distribution")
    rel = savefig(fig, "review_score_distribution")
    report.fig_ref("Review score histogram", rel)

    n_delivered = df["order_delivered_customer_date"].notna().sum()
    late_rate = df["is_late"].mean()
    report.p(f"\n- Orders with a delivered date: {n_delivered:,} / {len(df):,} ({n_delivered/len(df)*100:.1f}%)")
    report.p(f"- `is_late` rate among delivered orders: {late_rate*100:.2f}%")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    df["days_late"].clip(-30, 60).dropna().hist(bins=60, ax=ax, color="#DD8452")
    ax.axvline(0, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("days late (negative = early), clipped to [-30, 60]")
    ax.set_title("Delivery lateness distribution")
    rel = savefig(fig, "days_late_distribution")
    report.fig_ref("Days-late histogram (delivered orders only)", rel)

    cancel_rate = df["is_canceled_or_unavailable"].mean()
    report.p(f"\n- `is_canceled_or_unavailable` rate (all orders): {cancel_rate*100:.2f}%")

    df["bad_outcome_any"] = (
        df["bad_review"].fillna(False).astype(bool)
        | df["is_late"].fillna(False).astype(bool)
        | df["is_canceled_or_unavailable"]
    )
    report.p(f"- Composite `bad_outcome_any` (any of the above) rate (all orders): {df['bad_outcome_any'].mean()*100:.2f}%")


def section_target_overlap(df, report: Report):
    report.h2("3. How related are the candidate targets?")
    report.p("Key question from problem_framing.md: does late delivery actually predict "
              "low review score, or are they weakly linked (which would argue for treating "
              "them as separate problems rather than one composite target)?\n")
    report.p("**Leakage note:** `is_late` is only known *after* delivery, so even if it's a "
              "strong correlate of `bad_review` (as it turns out to be, below), it cannot be "
              "used directly as a model INPUT for a before-the-fact predictor -- it's an "
              "outcome, not a predictor. What this section is really establishing is *whether "
              "lateness is a meaningful causal channel worth building proxies for* (e.g. a "
              "seller's historical on-time rate, which IS known in advance), not whether "
              "`is_late` itself belongs in a feature set.\n")

    sub = df.dropna(subset=["review_score", "is_late"])
    grp = sub.groupby("is_late")["review_score"].agg(["mean", "median", "count"])
    rel = save_table(grp.reset_index(), "review_score_by_lateness")
    report.table_ref("Mean/median review_score, on-time vs. late", rel)

    bad_rate_by_late = sub.groupby("is_late")["bad_review"].mean() * 100
    for is_late_val, rate in bad_rate_by_late.items():
        label = "late" if is_late_val else "on-time"
        report.p(f"- bad_review rate when {label}: {rate:.2f}%")

    # contribution share: even if lateness strongly multiplies risk per-order,
    # if most orders are on-time, on-time orders can still contribute the
    # majority of TOTAL bad reviews. This matters for prioritisation.
    bad_counts_by_late = sub.groupby("is_late")["bad_review"].sum()
    total_bad = bad_counts_by_late.sum()
    n_by_late = sub.groupby("is_late").size()
    if total_bad > 0:
        report.p("\nContribution to TOTAL bad reviews (not just rate):\n")
        for is_late_val in [False, True]:
            if is_late_val not in bad_counts_by_late.index:
                continue
            label = "late" if is_late_val else "on-time"
            count = bad_counts_by_late.loc[is_late_val]
            share = count / total_bad * 100
            report.p(f"- {label} orders: {int(count):,} bad reviews out of {int(n_by_late.loc[is_late_val]):,} orders "
                      f"({share:.1f}% of all bad reviews)")

    corr_sub = df.dropna(subset=["days_late", "review_score"])
    if len(corr_sub) > 10:
        corr = corr_sub["days_late"].corr(corr_sub["review_score"])
        report.p(f"\n- Pearson correlation(days_late, review_score) = {corr:.3f} (n={len(corr_sub):,})")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    sub.boxplot(column="review_score", by="is_late", ax=ax)
    ax.set_xlabel("is_late")
    ax.set_ylabel("review_score")
    ax.set_title("Review score by lateness")
    plt.suptitle("")
    rel = savefig(fig, "review_score_by_lateness_box")
    report.fig_ref("Review score by lateness (boxplot)", rel)

    canc = df[df["is_canceled_or_unavailable"]]
    report.p(f"\n- Of {len(canc):,} canceled/unavailable orders, {canc['review_score'].notna().sum():,} "
              f"have a review score (mean {canc['review_score'].mean():.2f} where present).")


def section_seller_variance(df, raw, report: Report):
    report.h2("4. Seller-level variance (is this a seller problem?)")
    report.p("**Attribution caveat:** for orders with more than one seller, that order's single "
              "bad_review outcome is attributed to every seller involved (can't split blame from "
              "this data). See `build_seller_level_table` docstring. This affects ~2% of orders.\n")

    seller_stats = build_seller_level_table(raw, df)
    MIN_ORDERS = 10
    qualified = seller_stats[seller_stats["n_orders"] >= MIN_ORDERS].copy()

    report.p(f"- Total sellers: {len(seller_stats):,}")
    report.p(f"- Sellers with >= {MIN_ORDERS} orders (used below for rate stability): {len(qualified):,} "
              f"({len(qualified)/len(seller_stats)*100:.1f}% of sellers, but "
              f"{qualified['n_orders'].sum()/seller_stats['n_orders'].sum()*100:.1f}% of order volume)")

    rel = save_table(
        qualified.sort_values("bad_review_rate", ascending=False).head(20),
        "worst_20_sellers"
    )
    report.table_ref(f"Worst 20 sellers by bad_review_rate (n_orders>={MIN_ORDERS})", rel)

    # spread comparison vs category spread (section 5 computes its own;
    # here we just report seller spread on the same qualifying basis so the
    # two can be compared directly in the writeup)
    if len(qualified) > 0:
        spread = qualified["bad_review_rate"].max() - qualified["bad_review_rate"].min()
        report.p(f"\n- Seller bad_review_rate spread (min-max, n_orders>={MIN_ORDERS}): {spread*100:.1f} pp "
                  f"across {len(qualified):,} qualifying sellers")
        weighted_std = np.sqrt(np.average(
            (qualified["bad_review_rate"] - np.average(qualified["bad_review_rate"], weights=qualified["n_orders"])) ** 2,
            weights=qualified["n_orders"]
        ))
        report.p(f"- Volume-weighted std of seller bad_review_rate: {weighted_std*100:.2f} pp "
                  "(compare to the category-level spread in section 5 -- whichever grouping has "
                  "the larger weighted std carries more distinguishing signal)")

    # concentration / Pareto: what share of TOTAL bad reviews (within the
    # qualifying set) comes from the worst decile of sellers by rate?
    if len(qualified) >= 10:
        q_sorted = qualified.sort_values("bad_review_rate", ascending=False).reset_index(drop=True)
        total_bad_qualified = q_sorted["bad_review_count"].sum()
        decile_cut = max(1, len(q_sorted) // 10)
        worst_decile_bad = q_sorted.iloc[:decile_cut]["bad_review_count"].sum()
        worst_decile_orders = q_sorted.iloc[:decile_cut]["n_orders"].sum()
        share_of_bad = worst_decile_bad / total_bad_qualified * 100 if total_bad_qualified > 0 else float("nan")
        share_of_orders = worst_decile_orders / q_sorted["n_orders"].sum() * 100
        report.p(f"\n- Worst decile of qualifying sellers ({decile_cut} sellers, {share_of_orders:.1f}% of "
                  f"qualifying order volume) account for {share_of_bad:.1f}% of bad reviews among "
                  "qualifying sellers -- a concentration meaningfully above their order-volume share "
                  "would support a seller-risk-scoring approach; a share close to their volume share "
                  "would suggest bad outcomes are diffuse across sellers rather than concentrated in "
                  "a few bad actors.")

    # does seller experience (order volume) correlate with quality?
    if len(qualified) > 10:
        corr = qualified["n_orders"].corr(qualified["bad_review_rate"])
        report.p(f"\n- Correlation(seller order volume, bad_review_rate) = {corr:.3f} among qualifying "
                  "sellers (negative would suggest more experienced/bigger sellers are more reliable).")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    qualified["bad_review_rate"].hist(bins=30, ax=ax, color="#8172B2")
    ax.set_xlabel("bad_review_rate")
    ax.set_title(f"Seller bad_review_rate distribution (n_orders>={MIN_ORDERS})")
    rel = savefig(fig, "seller_bad_review_rate_distribution")
    report.fig_ref("Distribution of seller-level bad_review_rate", rel)

    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.scatter(qualified["n_orders"], qualified["bad_review_rate"], alpha=0.4, s=15, color="#4C72B0")
    ax.set_xscale("log")
    ax.set_xlabel("seller n_orders (log scale)")
    ax.set_ylabel("bad_review_rate")
    ax.set_title("Seller volume vs. bad_review_rate")
    rel = savefig(fig, "seller_volume_vs_bad_review_rate")
    report.fig_ref("Seller order volume vs. bad_review_rate (scatter)", rel)


def section_category_variance(df, report: Report):
    report.h2("5. Product category variance")

    sub = df.dropna(subset=["primary_category", "bad_review"])
    cat_stats = sub.groupby("primary_category").agg(
        n_orders=("order_id", "count"),
        bad_review_rate=("bad_review", "mean"),
    ).query("n_orders >= 30").sort_values("bad_review_rate", ascending=False)

    rel = save_table(cat_stats.reset_index(), "category_bad_review_rates")
    report.table_ref("bad_review rate by product category (n_orders>=30), sorted worst-first", rel)

    report.p(f"\n- Categories analysed: {len(cat_stats)} (after filtering n_orders>=30)")
    if len(cat_stats) > 0:
        report.p(f"- Worst category: `{cat_stats.index[0]}` ({cat_stats['bad_review_rate'].iloc[0]*100:.1f}%, "
                  f"n={cat_stats['n_orders'].iloc[0]})")
        report.p(f"- Best category: `{cat_stats.index[-1]}` ({cat_stats['bad_review_rate'].iloc[-1]*100:.1f}%, "
                  f"n={cat_stats['n_orders'].iloc[-1]})")
        spread = cat_stats["bad_review_rate"].max() - cat_stats["bad_review_rate"].min()
        report.p(f"- Spread (max-min bad_review_rate across categories): {spread*100:.1f} pp -- "
                  "a wide spread suggests category carries real signal; a narrow one suggests it doesn't.")

    fig, ax = plt.subplots(figsize=(6, 8))
    top = pd.concat([cat_stats.head(10), cat_stats.tail(10)])
    top["bad_review_rate"].sort_values().plot(kind="barh", ax=ax, color="#55A868")
    ax.set_xlabel("bad_review rate")
    ax.set_title("Best 10 / worst 10 categories (n>=30)")
    rel = savefig(fig, "category_bad_review_rates")
    report.fig_ref("Best/worst categories by bad_review rate", rel)


def section_price_freight(df, report: Report):
    report.h2("6. Price, freight, and payment structure")

    sub = df.dropna(subset=["bad_review"])
    for col in ["total_item_price", "total_freight_value", "max_installments"]:
        if col not in sub.columns:
            continue
        grp = sub.groupby("bad_review")[col].median()
        report.p(f"- Median `{col}`: bad_review=False -> {grp.get(False, float('nan')):.2f}, "
                  f"bad_review=True -> {grp.get(True, float('nan')):.2f}")

    fig, axes = plt.subplots(1, 2, figsize=(9, 3.5))
    sub.boxplot(column="total_item_price", by="bad_review", ax=axes[0])
    axes[0].set_ylim(0, sub["total_item_price"].quantile(0.95))
    axes[0].set_title("total_item_price")
    sub.boxplot(column="total_freight_value", by="bad_review", ax=axes[1])
    axes[1].set_ylim(0, sub["total_freight_value"].quantile(0.95))
    axes[1].set_title("total_freight_value")
    plt.suptitle("")
    fig.tight_layout()
    rel = savefig(fig, "price_freight_by_bad_review")
    report.fig_ref("Price/freight distributions by bad_review (clipped at p95)", rel)

    pay_stats = sub.groupby("primary_payment_type")["bad_review"].agg(["mean", "count"]).sort_values("mean", ascending=False)
    rel = save_table(pay_stats.reset_index(), "bad_review_by_payment_type")
    report.table_ref("bad_review rate by primary payment type", rel)


def section_distance(df, report: Report):
    report.h2("7. Customer-seller distance")
    report.p("Distance uses the primary (highest-price-item) seller's zip centroid vs. the "
              "customer's zip centroid -- an approximation for multi-seller orders (~2% of orders), "
              "same caveat as section 4.\n")

    n_missing = df["customer_seller_distance_km"].isna().sum()
    report.p(f"- Orders with a computed distance: {len(df) - n_missing:,} / {len(df):,} "
              f"({(len(df)-n_missing)/len(df)*100:.1f}%)")

    sub = df.dropna(subset=["customer_seller_distance_km", "bad_review"])
    if len(sub) > 10:
        med = sub.groupby("bad_review")["customer_seller_distance_km"].median()
        report.p(f"- Median distance (km): bad_review=False -> {med.get(False, float('nan')):.1f}, "
                  f"bad_review=True -> {med.get(True, float('nan')):.1f}")
        corr = sub["customer_seller_distance_km"].corr(sub["bad_review"].astype(float))
        report.p(f"- Correlation(distance_km, bad_review) = {corr:.3f} (n={len(sub):,})")

        # distance is a plausible proxy for delivery lateness risk -- check
        late_sub = df.dropna(subset=["customer_seller_distance_km", "is_late"])
        if len(late_sub) > 10:
            corr_late = late_sub["customer_seller_distance_km"].corr(late_sub["is_late"].astype(float))
            report.p(f"- Correlation(distance_km, is_late) = {corr_late:.3f} (n={len(late_sub):,}) -- "
                      "checking whether distance explains lateness, since distance (unlike is_late "
                      "itself) IS known at order time and could be a usable predictor.")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    sub.boxplot(column="customer_seller_distance_km", by="bad_review", ax=ax)
    ax.set_ylim(0, sub["customer_seller_distance_km"].quantile(0.95) if len(sub) > 0 else 1)
    ax.set_title("Distance by bad_review")
    plt.suptitle("")
    rel = savefig(fig, "distance_by_bad_review")
    report.fig_ref("Customer-seller distance by bad_review (clipped at p95)", rel)


def section_time_trends(df, report: Report):
    report.h2("8. Time trends")

    sub = df.dropna(subset=["order_purchase_timestamp", "bad_review"]).copy()
    sub["purchase_month"] = sub["order_purchase_timestamp"].dt.to_period("M").astype(str)
    monthly = sub.groupby("purchase_month").agg(
        n_orders=("order_id", "count"),
        bad_review_rate=("bad_review", "mean"),
    )
    rel = save_table(monthly.reset_index(), "monthly_bad_review_rate")
    report.table_ref("Monthly order volume and bad_review rate", rel)

    fig, ax1 = plt.subplots(figsize=(8, 3.5))
    ax2 = ax1.twinx()
    monthly["n_orders"].plot(ax=ax1, color="#4C72B0", label="n_orders")
    monthly["bad_review_rate"].plot(ax=ax2, color="#C44E52", label="bad_review_rate")
    ax1.set_ylabel("n_orders", color="#4C72B0")
    ax2.set_ylabel("bad_review_rate", color="#C44E52")
    ax1.set_xlabel("purchase month")
    ax1.set_title("Monthly volume vs. bad_review rate")
    fig.autofmt_xdate(rotation=45)
    rel = savefig(fig, "monthly_trend")
    report.fig_ref("Monthly volume and bad_review rate", rel)


def main():
    print("[eda] Loading raw tables...")
    raw = load_raw(RAW_DIR)

    print("[eda] Building order-level table...")
    df = build_order_level_table(raw)
    print(f"[eda] Order-level table: {df.shape[0]:,} rows x {df.shape[1]} cols")

    report = Report()

    print("[eda] Section 1: data quality...")
    section_data_quality(raw, df, report)

    print("[eda] Section 2: target candidates...")
    section_target_candidates(df, report)

    print("[eda] Section 3: target overlap...")
    section_target_overlap(df, report)

    print("[eda] Section 4: seller variance...")
    section_seller_variance(df, raw, report)

    print("[eda] Section 5: category variance...")
    section_category_variance(df, report)

    print("[eda] Section 6: price/freight/payment...")
    section_price_freight(df, report)

    print("[eda] Section 7: distance (partial)...")
    section_distance(df, report)

    print("[eda] Section 8: time trends...")
    section_time_trends(df, report)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    report.write(OUTPUT_DIR / "summary.md")
    print(f"\n[eda] Done. See {OUTPUT_DIR / 'summary.md'} and {FIG_DIR}/ and {TABLE_DIR}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())