"""
EDA stage: investigates the target-definition candidates and driver
variables laid out in docs/problem_framing.md.

Run:
    python -m src.eda.run_eda

Outputs (all under output/eda/):
    summary.md          human-readable findings, numbers inline
    tables/*.csv         supporting aggregated tables
    figures/*.png        supporting plots

Design intent: this script produces PLAIN NUMBERS AND PLOTS, not
conclusions -- interpretation happens in docs/problem_framing.md (revised
after reading this output) and eventually README.md. Keeping the split
this way makes it easy to see what's a measured fact vs. a judgment call.
"""

import sys
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.data.loader import RAW_DIR, load_raw, build_order_level_table

warnings.filterwarnings("ignore")

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output" / "eda"
FIG_DIR = OUTPUT_DIR / "figures"
TABLE_DIR = OUTPUT_DIR / "tables"

plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.3


def savefig(fig, name):
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    path = FIG_DIR / f"{name}.png"
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    return path.relative_to(OUTPUT_DIR)


def save_table(df, name):
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    path = TABLE_DIR / f"{name}.csv"
    df.to_csv(path, index=False)
    return path.relative_to(OUTPUT_DIR)


class Report:
    """Accumulates markdown sections in order, written out at the end."""
    def __init__(self):
        self.lines = ["# EDA Summary\n", "Auto-generated by `src/eda/run_eda.py`. Do not hand-edit.\n"]

    def h2(self, text):
        self.lines.append(f"\n## {text}\n")

    def p(self, text):
        self.lines.append(f"{text}\n")

    def table_ref(self, caption, rel_path):
        self.lines.append(f"\n*{caption}* -> `{rel_path}`\n")

    def fig_ref(self, caption, rel_path):
        self.lines.append(f"\n*{caption}* -> `{rel_path}`\n")

    def write(self, path):
        path.write_text("\n".join(self.lines))


# ---------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------

def section_data_quality(raw, df, report: Report):
    report.h2("1. Data quality checks")

    n_orders = len(df)
    report.p(f"- Total orders: {n_orders:,}")

    status_counts = df["order_status"].value_counts()
    rel = save_table(status_counts.rename("count").reset_index().rename(columns={"index": "order_status"}),
                      "order_status_counts")
    report.table_ref("Order status counts", rel)

    key_cols = [
        "primary_category", "total_item_price", "total_freight_value",
        "primary_payment_type", "max_installments", "customer_lat", "customer_lng",
        "n_distinct_sellers",
    ]
    missing = df[key_cols].isna().mean().sort_values(ascending=False) * 100
    report.p("\nMissingness (%) among candidate pre-outcome features:\n")
    for col, pct in missing.items():
        report.p(f"- `{col}`: {pct:.2f}%")

    n_missing_geo = df["customer_lat"].isna().sum()
    report.p(f"\n- Customer zip prefixes with no geolocation match: {n_missing_geo:,} ({n_missing_geo/n_orders*100:.2f}%)")

    n_zero_installments = (raw["order_payments"]["payment_installments"] == 0).sum()
    report.p(f"- Payment rows with `payment_installments == 0`: {n_zero_installments:,} "
             f"({n_zero_installments/len(raw['order_payments'])*100:.3f}% of payment rows) -- check payment_type for these.")
    if n_zero_installments > 0:
        zero_inst_types = raw["order_payments"].loc[
            raw["order_payments"]["payment_installments"] == 0, "payment_type"
        ].value_counts()
        rel = save_table(zero_inst_types.rename("count").reset_index().rename(columns={"index": "payment_type"}),
                          "zero_installment_payment_types")
        report.table_ref("Payment types among 0-installment rows", rel)

    geo = raw["geolocation"]
    n_dupe = geo.duplicated().sum()
    report.p(f"\n- Geolocation table: {len(geo):,} rows, {n_dupe:,} exact duplicates ({n_dupe/len(geo)*100:.1f}%), "
             f"collapsed to zip-prefix centroids for the `customer_lat`/`customer_lng` features used below.")


def section_target_candidates(df, report: Report):
    report.h2("2. Target candidate distributions")

    review_dist = df["review_score"].value_counts(dropna=False).sort_index()
    rel = save_table(review_dist.rename("count").reset_index().rename(columns={"index": "review_score"}),
                      "review_score_distribution")
    report.table_ref("Review score distribution (including NaN = no review)", rel)

    n_reviewed = df["review_score"].notna().sum()
    bad_review_rate = df["bad_review"].mean()
    report.p(f"- Orders with a review score: {n_reviewed:,} / {len(df):,} ({n_reviewed/len(df)*100:.1f}%)")
    report.p(f"- `bad_review` (score<=2) rate among reviewed orders: {bad_review_rate*100:.2f}%")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    review_dist.dropna().plot(kind="bar", ax=ax, color="#4C72B0")
    ax.set_xlabel("review_score")
    ax.set_ylabel("count")
    ax.set_title("Review score distribution")
    rel = savefig(fig, "review_score_distribution")
    report.fig_ref("Review score histogram", rel)

    n_delivered = df["order_delivered_customer_date"].notna().sum()
    late_rate = df["is_late"].mean()
    report.p(f"\n- Orders with a delivered date: {n_delivered:,} / {len(df):,} ({n_delivered/len(df)*100:.1f}%)")
    report.p(f"- `is_late` rate among delivered orders: {late_rate*100:.2f}%")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    df["days_late"].clip(-30, 60).dropna().hist(bins=60, ax=ax, color="#DD8452")
    ax.axvline(0, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("days late (negative = early), clipped to [-30, 60]")
    ax.set_title("Delivery lateness distribution")
    rel = savefig(fig, "days_late_distribution")
    report.fig_ref("Days-late histogram (delivered orders only)", rel)

    cancel_rate = df["is_canceled_or_unavailable"].mean()
    report.p(f"\n- `is_canceled_or_unavailable` rate (all orders): {cancel_rate*100:.2f}%")

    df["bad_outcome_any"] = (
        df["bad_review"].fillna(False).astype(bool)
        | df["is_late"].fillna(False).astype(bool)
        | df["is_canceled_or_unavailable"]
    )
    report.p(f"- Composite `bad_outcome_any` (any of the above) rate (all orders): {df['bad_outcome_any'].mean()*100:.2f}%")


def section_target_overlap(df, report: Report):
    report.h2("3. How related are the candidate targets?")
    report.p("Leakage note: `is_late` and `days_late` are only known after delivery, "
              "so they are diagnostic outcomes, not eligible model inputs for a pre-outcome "
              "risk model. This section uses them to explain review outcomes and to motivate "
              "eligible proxy features such as historical seller/route on-time rates.\n")

    sub = df.dropna(subset=["review_score", "is_late"])
    grp = sub.groupby("is_late")["review_score"].agg(["mean", "median", "count"])
    rel = save_table(grp.reset_index(), "review_score_by_lateness")
    report.table_ref("Mean/median review_score, on-time vs. late", rel)

    bad_rate_by_late = sub.groupby("is_late")["bad_review"].mean() * 100
    for is_late_val, rate in bad_rate_by_late.items():
        label = "late" if is_late_val else "on-time"
        report.p(f"- bad_review rate when {label}: {rate:.2f}%")

    bad_review_counts = (
        sub[sub["bad_review"]]
        .groupby("is_late")["order_id"]
        .count()
        .rename("bad_review_count")
    )
    n_bad_review = int(bad_review_counts.sum())
    n_late_bad = int(bad_review_counts.get(True, 0))
    n_ontime_bad = int(bad_review_counts.get(False, 0))
    if n_bad_review:
        report.p(f"\n- Late delivered orders contribute {n_late_bad:,} bad reviews "
                 f"({n_late_bad / n_bad_review * 100:.1f}% of bad reviews among orders with "
                 "both review and lateness known).")
        report.p(f"- On-time delivered orders contribute {n_ontime_bad:,} bad reviews "
                 f"({n_ontime_bad / n_bad_review * 100:.1f}%), so logistics is a major per-order "
                 "risk amplifier but not the whole dissatisfaction story.")

    corr_sub = df.dropna(subset=["days_late", "review_score"])
    if len(corr_sub) > 10:
        corr = corr_sub["days_late"].corr(corr_sub["review_score"])
        report.p(f"\n- Pearson correlation(days_late, review_score) = {corr:.3f} (n={len(corr_sub):,})")

    fig, ax = plt.subplots(figsize=(5, 3.5))
    sub.boxplot(column="review_score", by="is_late", ax=ax)
    ax.set_xlabel("is_late")
    ax.set_ylabel("review_score")
    ax.set_title("Review score by lateness")
    plt.suptitle("")
    rel = savefig(fig, "review_score_by_lateness_box")
    report.fig_ref("Review score by lateness (boxplot)", rel)

    canc = df[df["is_canceled_or_unavailable"]]
    report.p(f"\n- Of {len(canc):,} canceled/unavailable orders, {canc['review_score'].notna().sum():,} "
              f"have a review score (mean {canc['review_score'].mean():.2f} where present).")


def section_seller_variance(raw, df, report: Report):
    report.h2("4. Seller-level variance (is this a seller problem?)")

    single_seller_ids = (
        raw["order_items"]
        .groupby("order_id")
        .agg(
            n_distinct_sellers=("seller_id", "nunique"),
            seller_id=("seller_id", "first"),
        )
        .query("n_distinct_sellers == 1")
        .reset_index()[["order_id", "seller_id"]]
    )
    single_seller = df.merge(single_seller_ids, on="order_id", how="inner")
    report.p(f"- Single-seller orders used for this section: {len(single_seller):,} / {len(df):,} "
              f"({len(single_seller)/len(df)*100:.1f}%) -- multi-seller orders excluded here since "
              "the bad outcome can't be attributed to one seller from order-level data alone.")

    reviewed = single_seller.dropna(subset=["bad_review"]).copy()
    seller_stats = reviewed.groupby("seller_id").agg(
        n_orders=("order_id", "count"),
        bad_reviews=("bad_review", "sum"),
        bad_review_rate=("bad_review", "mean"),
        late_rate=("is_late", "mean"),
        median_item_price=("total_item_price", "median"),
        n_categories=("primary_category", "nunique"),
    ).sort_values(["bad_review_rate", "n_orders"], ascending=[False, False])
    seller_stats["share_of_all_bad_reviews"] = seller_stats["bad_reviews"] / seller_stats["bad_reviews"].sum()

    rel = save_table(seller_stats.reset_index(), "seller_bad_review_rates")
    report.table_ref("bad_review rate by seller, single-seller reviewed orders", rel)

    min_n = 30
    seller_stats_min_n = seller_stats.query("n_orders >= @min_n").copy()
    rel = save_table(seller_stats_min_n.reset_index(), "seller_bad_review_rates_min30")
    report.table_ref("seller bad_review rates with n_orders>=30", rel)

    report.p(f"\n- Sellers with at least one reviewed single-seller order: {len(seller_stats):,}")
    report.p(f"- Sellers with n_orders>={min_n}: {len(seller_stats_min_n):,}")
    if len(seller_stats_min_n) > 0:
        worst = seller_stats_min_n.iloc[0]
        best = seller_stats_min_n.sort_values(["bad_review_rate", "n_orders"], ascending=[True, False]).iloc[0]
        report.p(f"- Worst seller among n_orders>={min_n}: `{seller_stats_min_n.index[0]}` "
                 f"({worst['bad_review_rate']*100:.1f}%, n={int(worst['n_orders'])})")
        report.p(f"- Best seller among n_orders>={min_n}: `{best.name}` "
                 f"({best['bad_review_rate']*100:.1f}%, n={int(best['n_orders'])})")

    concentration_rows = []
    ordered = seller_stats.sort_values("bad_reviews", ascending=False)
    for pct in [0.01, 0.05, 0.10, 0.20]:
        n_sellers = max(1, int(np.ceil(len(ordered) * pct)))
        concentration_rows.append({
            "top_seller_share": pct,
            "n_sellers": n_sellers,
            "bad_reviews_captured": int(ordered.head(n_sellers)["bad_reviews"].sum()),
            "share_bad_reviews_captured": ordered.head(n_sellers)["bad_reviews"].sum() / ordered["bad_reviews"].sum(),
            "orders_captured": int(ordered.head(n_sellers)["n_orders"].sum()),
            "share_orders_captured": ordered.head(n_sellers)["n_orders"].sum() / ordered["n_orders"].sum(),
        })
    concentration = pd.DataFrame(concentration_rows)
    rel = save_table(concentration, "seller_bad_review_concentration")
    report.table_ref("concentration of bad reviews among sellers", rel)

    top_5pct = concentration.loc[concentration["top_seller_share"] == 0.05].iloc[0]
    report.p(f"- Top 5% of sellers by bad-review count account for "
             f"{top_5pct['share_bad_reviews_captured']*100:.1f}% of bad reviews and "
             f"{top_5pct['share_orders_captured']*100:.1f}% of reviewed single-seller orders.")

    seller_rate_corr = seller_stats_min_n[["bad_review_rate", "late_rate"]].dropna()
    if len(seller_rate_corr) > 10:
        corr = seller_rate_corr["bad_review_rate"].corr(seller_rate_corr["late_rate"])
        report.p(f"- Across sellers with n_orders>={min_n}, correlation between seller bad-review "
                 f"rate and observed late rate is {corr:.3f}. This is diagnostic only; a model "
                 "would need point-in-time historical rates.")


def section_category_variance(df, report: Report):
    report.h2("5. Product category variance")

    sub = df.dropna(subset=["primary_category", "bad_review"])
    cat_stats = sub.groupby("primary_category").agg(
        n_orders=("order_id", "count"),
        bad_review_rate=("bad_review", "mean"),
    ).query("n_orders >= 30").sort_values("bad_review_rate", ascending=False)

    rel = save_table(cat_stats.reset_index(), "category_bad_review_rates")
    report.table_ref("bad_review rate by product category (n_orders>=30), sorted worst-first", rel)

    cat_stats_min100 = cat_stats.query("n_orders >= 100")
    rel = save_table(cat_stats_min100.reset_index(), "category_bad_review_rates_min100")
    report.table_ref("bad_review rate by product category (n_orders>=100), sorted worst-first", rel)

    report.p(f"\n- Categories analysed: {len(cat_stats)} (after filtering n_orders>=30)")
    if len(cat_stats) > 0:
        report.p(f"- Worst category: `{cat_stats.index[0]}` ({cat_stats['bad_review_rate'].iloc[0]*100:.1f}%, "
                  f"n={cat_stats['n_orders'].iloc[0]})")
        report.p(f"- Best category: `{cat_stats.index[-1]}` ({cat_stats['bad_review_rate'].iloc[-1]*100:.1f}%, "
                  f"n={cat_stats['n_orders'].iloc[-1]})")
        spread = cat_stats["bad_review_rate"].max() - cat_stats["bad_review_rate"].min()
        report.p(f"- Spread (max-min bad_review_rate across categories): {spread*100:.1f} pp -- "
                  "a wide spread suggests category carries real signal; a narrow one suggests it doesn't.")
        report.p("- The extreme best/worst categories should be treated cautiously because the "
                 "n_orders>=30 table still includes small samples; use the n_orders>=100 table "
                 "when choosing robust business examples.")

    fig, ax = plt.subplots(figsize=(6, 8))
    top = pd.concat([cat_stats.head(10), cat_stats.tail(10)])
    top["bad_review_rate"].sort_values().plot(kind="barh", ax=ax, color="#55A868")
    ax.set_xlabel("bad_review rate")
    ax.set_title("Best 10 / worst 10 categories (n>=30)")
    rel = savefig(fig, "category_bad_review_rates")
    report.fig_ref("Best/worst categories by bad_review rate", rel)


def section_price_freight(df, report: Report):
    report.h2("6. Price, freight, and payment structure")

    sub = df.dropna(subset=["bad_review"])
    for col in ["total_item_price", "total_freight_value", "max_installments"]:
        if col not in sub.columns:
            continue
        grp = sub.groupby("bad_review")[col].median()
        report.p(f"- Median `{col}`: bad_review=False -> {grp.get(False, float('nan')):.2f}, "
                  f"bad_review=True -> {grp.get(True, float('nan')):.2f}")

    fig, axes = plt.subplots(1, 2, figsize=(9, 3.5))
    sub.boxplot(column="total_item_price", by="bad_review", ax=axes[0])
    axes[0].set_ylim(0, sub["total_item_price"].quantile(0.95))
    axes[0].set_title("total_item_price")
    sub.boxplot(column="total_freight_value", by="bad_review", ax=axes[1])
    axes[1].set_ylim(0, sub["total_freight_value"].quantile(0.95))
    axes[1].set_title("total_freight_value")
    plt.suptitle("")
    fig.tight_layout()
    rel = savefig(fig, "price_freight_by_bad_review")
    report.fig_ref("Price/freight distributions by bad_review (clipped at p95)", rel)

    pay_stats = sub.groupby("primary_payment_type")["bad_review"].agg(["mean", "count"]).sort_values("mean", ascending=False)
    rel = save_table(pay_stats.reset_index(), "bad_review_by_payment_type")
    report.table_ref("bad_review rate by primary payment type", rel)


def section_distance(df, report: Report):
    report.h2("7. Customer-seller distance (partial -- needs seller geolocation)")
    report.p("**Known gap:** distance requires the seller's own zip-prefix centroid joined in "
              "the same way as the customer's, which this pass doesn't yet do (order-level table "
              "doesn't carry seller_zip_code_prefix after the items aggregation -- same root cause "
              "as the seller-level gap in section 4). Deferred until we decide seller-level analysis "
              "is worth the extra join complexity.")


def section_time_trends(df, report: Report):
    report.h2("8. Time trends")

    sub = df.dropna(subset=["order_purchase_timestamp", "bad_review"]).copy()
    sub["purchase_month"] = sub["order_purchase_timestamp"].dt.to_period("M").astype(str)
    monthly = sub.groupby("purchase_month").agg(
        n_orders=("order_id", "count"),
        bad_review_rate=("bad_review", "mean"),
    )
    rel = save_table(monthly.reset_index(), "monthly_bad_review_rate")
    report.table_ref("Monthly order volume and bad_review rate", rel)

    fig, ax1 = plt.subplots(figsize=(8, 3.5))
    ax2 = ax1.twinx()
    monthly["n_orders"].plot(ax=ax1, color="#4C72B0", label="n_orders")
    monthly["bad_review_rate"].plot(ax=ax2, color="#C44E52", label="bad_review_rate")
    ax1.set_ylabel("n_orders", color="#4C72B0")
    ax2.set_ylabel("bad_review_rate", color="#C44E52")
    ax1.set_xlabel("purchase month")
    ax1.set_title("Monthly volume vs. bad_review rate")
    fig.autofmt_xdate(rotation=45)
    rel = savefig(fig, "monthly_trend")
    report.fig_ref("Monthly volume and bad_review rate", rel)


def main():
    print("[eda] Loading raw tables...")
    raw = load_raw(RAW_DIR)

    print("[eda] Building order-level table...")
    df = build_order_level_table(raw)
    print(f"[eda] Order-level table: {df.shape[0]:,} rows x {df.shape[1]} cols")

    report = Report()

    print("[eda] Section 1: data quality...")
    section_data_quality(raw, df, report)

    print("[eda] Section 2: target candidates...")
    section_target_candidates(df, report)

    print("[eda] Section 3: target overlap...")
    section_target_overlap(df, report)

    print("[eda] Section 4: seller variance...")
    section_seller_variance(raw, df, report)

    print("[eda] Section 5: category variance...")
    section_category_variance(df, report)

    print("[eda] Section 6: price/freight/payment...")
    section_price_freight(df, report)

    print("[eda] Section 7: distance (partial)...")
    section_distance(df, report)

    print("[eda] Section 8: time trends...")
    section_time_trends(df, report)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    report.write(OUTPUT_DIR / "summary.md")
    print(f"\n[eda] Done. See {OUTPUT_DIR / 'summary.md'} and {FIG_DIR}/ and {TABLE_DIR}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
